### ISSUE TITLE
attribute with typeof() variable?

### ISSUE THREAD

**Issue by jeanfabre** [anchan828/property-drawer-collection#9]
Hi,

 Very impressed by your attributes! 

 I stumbled upeon your work while searching on how to create an attribute like "RequireComponent" , and how to get the type value within  the script to use it in a propertyDrawer.

 Any hints or an example of a RequireComponent attribute would be great :)

 Thanks 

 Jean Fabre

**Comment by anchan828** [comment]
Hi :)

Thank you for your message.

> how to get the type value within the script to use it in a propertyDrawer.

you may have already resolved, but can as below.

```cs
using UnityEngine;

public class GetTypeExample : MonoBehaviour
{
    [GetType(typeof(Component)), SerializeField]
    private Camera camera;

    [GetType, SerializeField]
    private Camera camera2;
}
```

```cs
using System;
using UnityEngine;

public class GetTypeAttribute : PropertyAttribute
{
    public Type type;
    public GetTypeAttribute() { }

    public GetTypeAttribute(Type type)
    {
        this.type = type;
    }
}
```
```cs
using System;
using UnityEngine;
using UnityEditor;

[CustomPropertyDrawer(typeof(GetTypeAttribute))]
public class GetTypeDrawer : PropertyDrawer
{
    GetTypeAttribute attribute
    {
        get { return (GetTypeAttribute)base.attribute; }
    }

    private Type type
    {
        get
        {
            return attribute.type ?? fieldInfo.FieldType;
        }
    }


    public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
    {
        // do something...
        EditorGUI.PropertyField(position, property, label);
    }
}
```

**Comment by jeanfabre** [comment]
Hi,

Thanks for your answer, but I did not explained myself properly, sorry :)

I have a serialized class where I need to let the author define the type, I would like to use "RequireComponent" attribute but it's not available for public properties, and my problem is then trying to reverse engineer this attribute, and namely how to extract the type from a relative property using .FindPropertyRelative() or via the fieldInfo, it seems I can only get Unity objects or simple types like bools, strings, ints, etc

Bye,

 Jean

**Comment by jeanfabre** [comment]
Hi,

Thanks :) deleted my previous comment,  I need to get my head around this first.

Have a good day,

 Jean

**Comment by jeanfabre** [comment]
Hi,

 Works :) Thanks for your time!

 Bye,

 Jean
